### Вычисления с помощью Numpy

Задание 1

In [56]:
import numpy as np

In [35]:
a = np.array([[1, 2, 3, 3, 1],
             [6, 8, 11, 10, 7]])
a = a.transpose()
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [21]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

Задание 2

In [22]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [23]:
a_centered.shape

(5, 2)

Задание 3

In [47]:
a_centered_sp = np.sum(a_centered[:, 0] * a_centered[:, 1])

In [49]:
a_centered_sp

8.0

In [50]:
result = a_centered_sp / (5 - 1)
result

2.0

Задание 4

In [51]:
cov_check = np.cov(a.transpose())
cov_check

array([[1. , 2. ],
       [2. , 4.3]])

In [52]:
cov_check[0, 1]

2.0