In [1]:
import numpy as np

## ** Задание на повторение материала

Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [2]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [3]:
a1 = a.reshape((3, 4))
a2 = a.reshape((2, 6))
a3 = a.reshape((4, 3))
a4 = a.reshape((1, 12))
a5 = a.reshape((6, 2))

Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [4]:
b1 = a.reshape((3, -1))
b2 = a.reshape((-1, 6))
b3 = a.reshape((4, -1))
b4 = a.reshape((-1, 12))
b5 = a.reshape((6, -1))

Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

### Да

Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [5]:
c = np.random.rand(3, 4)
d = c.reshape(1, 12)
d.size

12

In [6]:
d

array([[0.49278154, 0.30456651, 0.43411195, 0.63488445, 0.85596132,
        0.88882501, 0.5362686 , 0.01166474, 0.82629827, 0.92792894,
        0.33130925, 0.89598775]])

Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [7]:
a = np.arange(20, 0, -2)

In [8]:
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [53]:
b = np.arange(20, 1, -2).reshape(1, 10)

In [54]:
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [55]:
b[0][1]

18

In [56]:
a[1]

1

Массив b является подмассивом, в отличие от a

Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [17]:
a = np.zeros((2, 2))
b = np.ones((3, 2))

In [18]:
a

array([[0., 0.],
       [0., 0.]])

In [19]:
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [32]:
np.vstack((a, b)).size

10

Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [35]:
a = np.arange(0, 12)
A = a.reshape((4, 3))

In [36]:
At = A.transpose()

In [38]:
B = np.matmul(A, At)

In [40]:
B.size

16

In [59]:
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

Из-за корреляции данных и остутствия шума в них не выйдет обратить матрицу B.

Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [60]:
np.random.seed(42)

Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [67]:
c = np.random.randint(0, 16, size=16)
c

array([12,  7, 14,  2, 13,  0,  3,  1,  7,  3,  1, 13,  5,  5,  9,  3])

Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [69]:
C = c.reshape((4, 4))
C

array([[12,  7, 14,  2],
       [13,  0,  3,  1],
       [ 7,  3,  1, 13],
       [ 5,  5,  9,  3]])

In [70]:
D = B + (C * 10)
D

array([[125,  84, 163,  52],
       [144,  50, 116, 132],
       [ 93, 116, 159, 342],
       [ 82, 172, 302, 332]])

In [89]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.00530561,  0.00333288,  0.00394671, -0.00622171],
       [ 0.03521848, -0.03758695,  0.02779685, -0.01920604],
       [-0.01386906,  0.01530626, -0.01753471,  0.0141495 ],
       [-0.0069403 ,  0.00472641,  0.00057468,  0.00162792]])

In [73]:
np.linalg.det(D)

159393600.0000001

In [78]:
np.linalg.matrix_rank(D)

4

Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.


In [90]:
D_inv

array([[ 0.00530561,  0.00333288,  0.00394671, -0.00622171],
       [ 0.03521848, -0.03758695,  0.02779685, -0.01920604],
       [-0.01386906,  0.01530626, -0.01753471,  0.0141495 ],
       [-0.0069403 ,  0.00472641,  0.00057468,  0.00162792]])

In [91]:
for i in range(0, 4):
    for j in range(0, 4):
        if (D_inv[i][j] <= 0):
            D_inv[i][j] = 0
        else: D_inv[i][j] = 1


In [92]:
D_inv.astype(int)

array([[1, 1, 1, 0],
       [1, 0, 1, 0],
       [0, 1, 0, 1],
       [0, 1, 1, 1]])

In [93]:
E = np.where(D_inv, B, C)

In [101]:
"D_inv", D_inv, "_" * 40, "B", B, "_" * 40, "C", C, "_" * 40, "E", E

('D_inv',
 array([[1., 1., 1., 0.],
        [1., 0., 1., 0.],
        [0., 1., 0., 1.],
        [0., 1., 1., 1.]]),
 '________________________________________',
 'B',
 array([[  5,  14,  23,  32],
        [ 14,  50,  86, 122],
        [ 23,  86, 149, 212],
        [ 32, 122, 212, 302]]),
 '________________________________________',
 'C',
 array([[12,  7, 14,  2],
        [13,  0,  3,  1],
        [ 7,  3,  1, 13],
        [ 5,  5,  9,  3]]),
 '________________________________________',
 'E',
 array([[  5,  14,  23,   2],
        [ 14,   0,  86,   1],
        [  7,  86,   1, 212],
        [  5, 122, 212, 302]]))